name: ccv1
channels:
  - conda-forge
  - nvidia
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - python-dotenv=0.21.0
  - numpy=1.23.4
  - pytorch-lightning=2.0.2
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - torchmetrics=0.11.2
  - transformers=4.24.0
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - pandas=1.5.3
  - matplotlib=3.7.1
  - wandb=0.15.0
  - mypy
  - ipykernel
  - ipywidgets